# -*- mode: ruby -*-
# vi: set ft=ruby :
require 'yaml'

if File.exists? ('vagrant.yml')
	settings = YAML.load_file 'vagrant.yml'
else
	settings = {}
end

ram = settings['ram'] || 2048

Vagrant.configure("2") do |config|
	config.vm.box = "suse/sles12sp1"
	config.ssh.forward_agent = true
	config.vm.synced_folder './', '/vagrant', type: 'rsync', disabled: true

	unless settings['suse_register'].nil?
		config.vm.provision :shell do |shell|
			arglist = settings['suse_register'].map {|k, v| "-a '#{k}=#{v}'"} + ['-n']
			shell.inline = 'suse_register ' + arglist.join(' ')
		end
	end

	config.vm.provider :virtualbox do |vb|
		vb.gui = true
		vb.memory = ram
	end

end
