Vagrant.configure(2) do |config|
	config.vm.box = "ubuntu/xenial64"
	config.vm.provider "virtualbox" do |vb|
		vb.gui = true
		vb.memory = "1024"
	end
#	config.vm.network "public_network"
#	config.ssh.private_key_path = "/Users/bborbe/.ssh/id_rsa"
#	config.ssh.insert_key = true
end
