Vagrant.configure(2) do |config|
  config.vm.box = "ubuntu/xenial64"
  config.vm.provider "virtualbox" do |vb|
    vb.gui = true
    vb.memory = "1024"
  end
  config.vm.provision "shell", inline: <<-SHELL
    DEBIAN_FRONTEND=noninteractive apt-get update --quiet
    DEBIAN_FRONTEND=noninteractive apt-get upgrade --quiet --yes
    DEBIAN_FRONTEND=noninteractive apt-get install --quiet --yes --no-install-recommends \
    file \
    sudo
    DEBIAN_FRONTEND=noninteractive apt-get autoremove --yes 
    DEBIAN_FRONTEND=noninteractive apt-get clean
  SHELL
end
