# -*- mode: ruby -*-
# vi: set ft=ruby :

# Vagrantfile API/syntax version. Don't touch unless you know what you're doing!
VAGRANTFILE_API_VERSION = "2"

Vagrant.configure(VAGRANTFILE_API_VERSION) do |config|
  # Every Vagrant virtual environment requires a box to build off of.
  config.vm.box = "ubuntu/trusty64"

  config.vm.hostname = "localdev-ubuntu-X"

  config.vm.provider :virtualbox do |vb|
    # Don't boot with headless mode
    #vb.gui = true 

    # Name in VirtualBox Gui
    vb.name = "localdev-ubuntu-X"

    # Number of CPUs
    vb.cpus = 2                                                                 
    
    # Memory                                                                    
    vb.memory = 2048 
 
    # Use VBoxManage to customize the VM:
    vb.customize ["modifyvm", :id, "--nic1", "nat"]
    #vb.customize ["modifyvm", :id, "--nic2", "hostonly"] 
  end

  # Pre-provision, bootstrap puppet
  config.vm.provision :shell, :path => "resources/vagrant/pre_provision.sh"

  config.vm.provision "puppet" do |puppet|
    puppet.manifests_path = "resources/puppet"
    puppet.manifest_file  = "localdev.pp"
    puppet.module_path = "resources/puppet/modules"
  end

  # post provision 
  config.vm.provision :shell, :path => "resources/vagrant/post_provision.sh"

	# port forwarding
  config.vm.network "forwarded_port", guest: 80, host: 8080, auto_correct: true
  config.vm.network "forwarded_port", guest: 443, host: 8443, auto_correct: true

  # Share an additional folder to the guest VM. The first argument is
  # the path on the host to the actual folder. The second argument is
  # the path on the guest to mount the folder. And the optional third
  # argument is a set of non-required options.
  config.vm.synced_folder "./data", "/data"

  config.ssh.shell = "bash -c 'BASH_ENV=/etc/profile exec bash'"
end
